# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rem-D Repo
email: andrewreeman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my lovely repo for projects using git. I also sleep with the enemy using bitbucket. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrewreeman.com" # the base hostname & protocol for your site
twitter_username: AndrewReeman
github_username:  andrewreeman

# Build settings
markdown: kramdown
